# Disables install scripts
enableScripts: false
# Informs yarn 3 to use node-modules format
nodeLinker: node-modules
# Informs yarn 3 where the executable is located
yarnPath: .yarn/releases/yarn-3.2.4.cjs
# Disables telemetry data sent to yarn out of an abundance of caution
enableTelemetry: false
