compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

enableTelemetry: false

logFilters:
  - code: YN0004
    level: discard

nodeLinker: node-modules

npmAuditIgnoreAdvisories:
  - 1088783
  - 1092429
  - 1089718
  - 1092461
  - popper.js (deprecation)
  - mini-create-react-context (deprecation)
  - uuid (deprecation)
  - "@npmcli/move-file (deprecation)"
  - core-js (deprecation)
  - "@material-ui/core (deprecation)"
  - "@material-ui/styles (deprecation)"
  - "@material-ui/system (deprecation)"
  - "@ensdomains/ens (deprecation)"
  - "@ensdomains/resolver (deprecation)"
  - testrpc (deprecation)
  - cids (deprecation)
  - multibase (deprecation)
  - multicodec (deprecation)
  - eth-sig-util (deprecation)
  - "@metamask/controller-utils (deprecation)"
  - safe-event-emitter (deprecation)
  - crypto (deprecation)
  - webextension-polyfill-ts (deprecation)

npmRegistries:
  "https://npm.pkg.github.com":
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_PACKAGE_READ_TOKEN-}"

npmScopes:
  metamask:
    npmRegistryServer: "${METAMASK_NPM_REGISTRY:-https://registry.yarnpkg.com}"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-allow-scripts.cjs
    spec: "https://raw.githubusercontent.com/LavaMoat/LavaMoat/main/packages/yarn-plugin-allow-scripts/bundles/@yarnpkg/plugin-allow-scripts.js"
  - path: .yarn/plugins/@yarnpkg/plugin-engines.cjs
    spec: "https://raw.githubusercontent.com/devoto13/yarn-plugin-engines/main/bundles/%40yarnpkg/plugin-engines.js"

yarnPath: .yarn/releases/yarn-4.0.0-rc.50.cjs
