name: Bug Report
description: Using MetaMask, but it's not working as you expect?
title: "[Bug]: "
labels: ["bug", "flask"]
body:
 - type: markdown
   attributes:
     value: |
       Thanks for taking the time to fill out this bug report!
 - type: markdown
   attributes:
     value: |
       ## **Before Submitting:**

       * Please search to make sure this issue has not been opened already.
       * If this is a question about how to integrate MetaMask with your project, please ask in our [Community forum](https://community.metamask.io/c/developer-questions/) instead. This will get your question answered more quickly and make it easier for other devs to find the answer in the future.
 - type: textarea
   id: what-happened
   attributes:
     label: Describe the bug
     description: What happened? What did you expect to happen? Please include a complete description of the problem along with any relevant additional context.
     placeholder: Tell us what you see!
   validations:
     required: true
 - type: textarea
   id: reproduce
   attributes:
     label: Steps to reproduce
     description: List all steps needed to reproduce the problem
     placeholder: |
       1. Go to '...'
       2. Click on '....'
       3. Scroll down to '....'
       4. See error
     value: |
       1.
   validations:
     required: true
 - type: textarea
   id: error
   attributes:
     label: Error messges or log output
     description: Please copy and paste any relevant error messages or log output. This will be automatically formatted, so there is no need for backticks.
     render: shell
 - type: input
   id: version
   attributes:
     label: Version
     description: What version of MetaMask are you running? You can find the version in "Settings" > "About"
   validations:
     required: true
 - type: dropdown
   id: browsers
   attributes:
     label: What browsers have you seen the problem on?
     multiple: true
     options:
       - Chrome
       - Firefox
       - Microsoft Edge
       - Brave
       - Other
