name: Notify MMI team via Slack

on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - reopened
      - synchronize
      - labeled

jobs:
  process-label:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Notify MMI team via Slack
        if: contains(github.event.pull_request.labels.*.name, 'team-mmi')
        uses: slackapi/slack-github-action@v1.25.0
        with:
          status: custom
          fields: repo,message,commit,author,action
          payload: |
            {
              "text": "A PR with label 'team-mmi' was added and requires review: ${{ github.repository }}#${{ github.event.pull_request.number }}",
              "attachments": [
                {
                  "color": "#2eb886",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.repository }}",
                      "short": true
                    },
                    {
                      "title": "PR",
                      "value": "<${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.MMI_LABEL_SLACK_WEBHOOK_URL }}