name: "CLA Signature Bot"
on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened,closed,synchronize]

jobs:
  CLABot:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Signature Bot"
        uses: roblox/cla-signature-bot@v2.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: 'cla.json'
          url-to-cladocument: 'https://metamask.io'
          # This branch can't have protections, commits are made directly to the specified branch.
          branch: 'cla-signatures'
          whitelist: dependabot
          blockchain-storage-flag: false
