name: Create Release Branch

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: 'The base branch, tag, or SHA for git operations.'
        required: true
      semver-version:
        description: 'A semantic version. eg: x.x.x'
        required: true
      next-semver-version:
        description: 'Another semantic version. eg: x.x.x (next release version number)'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          # This is to guarantee that the most recent tag is fetched.
          # This can be configured to a more reasonable value by consumers.
          fetch-depth: 0
          # We check out the specified branch, which will be used as the base
          # branch for all git operations and the release PR.
          ref: ${{ github.event.inputs.base-branch }}
      - name: Get Node.js version
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Create Release Branch
        id: create-release-branch
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./development/create-release-branch.sh ${{ github.event.inputs.semver-version }}
      - name: Save next release version number in a text file
        run: echo "${{ github.event.inputs.next-semver-version }}" > next-semver-version.txt
      - name: Upload text file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: next-semver-version
          path: next-semver-version.txt
