name: Cherry Pick Commit

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  cherry-pick:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ vars.GITHUB_REF }}
          fetch-depth: 0
          token: ${{ secrets.BUG_REPORT_TOKEN }}
      - name: Get Node.js version
        id: nvm
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> "$GITHUB_OUTPUT"
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.nvm.outputs.NODE_VERSION }}
      - name: Create Cherry Pick PR
        id: create-cherry-pick-pr
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./.github/scripts/create-cherry-pick-pr.sh Version-v11.14.2 378bb27 24171
