name: Crowdin Action

permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - develop
  schedule:
    - cron: "0 */12 * * *"

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: crowdin action
      uses: crowdin/github-action@9237b4cb361788dfce63feb2e2f15c09e2fe7415
      with:
        upload_translations: true
        download_translations: true
        github_user_name: metamaskbot
        github_user_email: metamaskbot@users.noreply.github.com
      env:
        GITHUB_ACTOR: metamaskbot
        GITHUB_TOKEN: ${{ secrets.METAMASKBOT_CROWDIN_TOKEN }}
        CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
        CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
