name: Fitness Functions CI

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn

      - name: Run fitness functions
        env:
          BASE_REF: ${{ github.event.pull_request.base.ref }}
        run: |
          # The following command generates a diff of changes between the common
          # ancestor of $BASE_REF and HEAD, and the current commit (HEAD), for
          # files in the current directory and its subdirectories. The output is
          # then saved to a file called "diff".
          git diff "$(git merge-base "origin/$BASE_REF" HEAD)" HEAD -- . > ./diff
          npm run fitness-functions -- "ci" "./diff"