name: Label PR

on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/github-script@v6
        env:
          HEAD_REF: ${{ github.event.pull_request.head.ref }}
        with:
          script: npm run label-prs -- process.env.HEAD_REF