name: Validate Conventional Commit Title
on:
  pull_request:
    types: [opened, edited, reopened]

jobs:
  pr-title-linter:
    runs-on: ubuntu-latest
    steps:
    - uses: amannn/action-semantic-pull-request@v5.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
